apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
data:
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVFqaURlTGdhMHFXazBualVsZ2Y5TklURG0wajBRazVUWFdqQUlFVkJoejN0WHViOWJIWWtoWVI4UkU3MFBhVzZGT0lWUlhXMExJYnNMb25IOEZnaDVGQjAwdGVsbnRiWEU=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfMGJiZTMzY2MzOWY4YmQ5OTQzZGMzYjJiZjkxYjhhMmFlMWViZjRmZTVmMTY4NmNiMzUxMzIyYTk1MjJkYWQ5YQ==
