apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-delivery
  template:
    metadata:
      labels:
        app: mongo-delivery
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-delivery-pvc
