apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: default
data:
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  EMAIL_USER: "navmann177@gmail.com"
  TWILIO_PHONE_NUMBER: "+19125590933"
  TWILIO_ACCOUNT_SID: "AC74d7aeae0198f74ab72a5c3b210482b0"
