apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: manilkanav/notification-service:latest
          ports:
            - containerPort: 4010
          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: notification-secret
