apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-restaurant
  template:
    metadata:
      labels:
        app: mongo-restaurant
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-restaurant-pvc
